name = "insight-lite"
main = "backend/index.ts"
compatibility_date = "2025-11-15"
workers_dev = true

[vars]
JWT_SECRET = "8cb92eb311e1a8106f160b01da419580707c8e5b225917dccdc5b211595f76cfe6c12c26ae9aa3859d358ea7a18183b6209673c9bbc90596d516e0a55b575f79"
CLOUDFLARE_ACCOUNT_ID = "18c8e61a3669253dcfd0c7eec6be36a3"

[[kv_namespaces]]
binding = "USER_STORE"
id = "6dd308dd1c0a4d6c83cb3ffd82847530"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ih-pdfs"
